# Generated by Django 3.2.4 on 2023-07-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='avatar',
        ),
    ]
