# Generated by Django 3.2.4 on 2023-07-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='images',
            new_name='image',
        ),
    ]
