# Generated by Django 3.2.4 on 2023-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chat',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
