# Generated by Django 3.2.4 on 2023-07-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20230717_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='unread_messages',
        ),
    ]
