# Generated by Django 3.2.4 on 2023-07-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='tweet_pictures'),
        ),
    ]
