# Generated by Django 3.2.4 on 2023-07-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_tweet_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='picture',
        ),
    ]
