# Generated by Django 3.2.4 on 2023-07-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_remove_tweet_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='tweet_pictures'),
        ),
    ]
