# Generated by Django 3.2.4 on 2023-07-22 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0018_alter_tweet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='tweets.tweet'),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='retweets_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
